from flaskblog import db
from flaskblog.models import User, Post

db.drop_all()
db.create_all()
user_1 = User(username='Marcin', email='marcin@gmail.com', password='p@ssw0rd')
db.session.add(user_1)
db.session.commit()
user_2 = User(username='Jan', email='jan@gmail.com', password='p@ssw0rd')
db.session.add(user_2)
db.session.commit()
user_3 = User(username='Zofia', email='zofia@gmail.com', password='p@ssw0rd')
db.session.add(user_3)
db.session.commit()

post_1 = Post(title='Post One Title', content='Post One Content', user_id=user_1.id)
db.session.add(post_1)
db.session.commit()
post_2 = Post(title='Post Two Title', content='Post Two Content', user_id=user_1.id)
db.session.add(post_2)
db.session.commit()
post_3 = Post(title='Post Three Title', content='Post Three Content', user_id=user_2.id)
db.session.add(post_3)
db.session.commit()
post_4 = Post(title='Post Four Title', content='Post Four Content', user_id=user_1.id)
db.session.add(post_4)
db.session.commit()
post_5 = Post(title='Post Five Title', content='Post Five Content', user_id=user_2.id)
db.session.add(post_5)
db.session.commit()
post_6 = Post(title='Post Six Title', content='Post Six Content', user_id=user_3.id)
db.session.add(post_6)
db.session.commit()
post_4 = Post(title='Post Seven Title', content='Post Seven Content', user_id=user_1.id)
db.session.add(post_4)
db.session.commit()
